### ISSUE TITLE
The latest version will cause the server to crash

### ISSUE THREAD

**Issue by lsw46** [PikyCZ/MobPlugin#18]
22:03:46 [EMERGENCY] Exception happened while ticking server
22:03:46 [ALERT] java.lang.NoClassDefFoundError: cn/nukkit/timings/Timings
        at de.kniffo80.mobplugin.entities.animal.WalkingAnimal.entityBaseTick(Walking
Animal.java:38)
        at de.kniffo80.mobplugin.entities.animal.WalkingAnimal.onUpdate(WalkingAnimal
.java:74)
        at cn.nukkit.level.Level.doTick(Level.java:753)
        at cn.nukkit.Server.checkTickUpdates(Server.java:933)
        at cn.nukkit.Server.tick(Server.java:1008)
        at cn.nukkit.Server.tickProcessor(Server.java:800)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.ClassNotFoundException: cn.nukkit.timings.Timings
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more

22:03:46 [ALERT]
"Thread-14" Id=27 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.Player$1.run(Player.java:500)

"threadDeathWatcher-3-1" Id=26 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run
(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Unknown Source)

"nioEventLoopGroup-2-1" Id=25 RUNNABLE (in native)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@12591ac8
        -  locked java.util.Collections$UnmodifiableSet@5a7fe64f
        -  locked sun.nio.ch.WindowsSelectorImpl@38145825
        at sun.nio.ch.SelectorImpl.select(Unknown Source)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
        ...

"Nukkit Asynchronous Task Handler #7" Id=24 WAITING on java.util.concurrent.Synchrono
usQueue$TransferStack@41330d4f
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41330d4f
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown S
ource)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Sourc
e)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #5" Id=22 WAITING on java.util.concurrent.Synchrono
usQueue$TransferStack@41330d4f
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41330d4f
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown S
ource)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Sourc
e)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #4" Id=21 WAITING on java.util.concurrent.Synchrono
usQueue$TransferStack@41330d4f
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41330d4f
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown S
ource)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Sourc
e)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #2" Id=19 WAITING on java.util.concurrent.Synchrono
usQueue$TransferStack@41330d4f
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41330d4f
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown S
ource)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Sourc
e)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #1" Id=18 WAITING on java.util.concurrent.Synchrono
usQueue$TransferStack@41330d4f
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41330d4f
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown S
ource)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Sourc
e)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"RakNet Thread #14" Id=14 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:9
6)
        at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
        at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
        at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"Console" Id=11 RUNNABLE (in native)
        at org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method)
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.jav
a:811)
        at org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:8
42)
        at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSuppo
rt.java:97)
        at jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214)
        at jline.WindowsTerminal.access$000(WindowsTerminal.java:54)
        at jline.WindowsTerminal$1.read(WindowsTerminal.java:156)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166
)
        -  locked jline.internal.NonBlockingInputStream@1b66c0fb
        ...

"NonBlockingInputStreamThread" Id=13 WAITING on jline.internal.NonBlockingInputStream
@1b66c0fb owned by "Console" Id=11
        at java.lang.Object.wait(Native Method)
        -  waiting on jline.internal.NonBlockingInputStream@1b66c0fb
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)

        at java.lang.Thread.run(Unknown Source)

"Thread-0" Id=10 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:224)
        at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)

"Attach Listener" Id=5 RUNNABLE

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@3e0e1046
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@3e0e1046
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@24c1b2d2
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@24c1b2d2
        at java.lang.Object.wait(Unknown Source)
        at java.lang.ref.Reference.tryHandlePending(Unknown Source)
        at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"main" Id=1 RUNNABLE
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
        at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:110)
        at cn.nukkit.Server.tickProcessor(Server.java:814)
        at cn.nukkit.Server.start(Server.java:779)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by lsw46** [comment]
0.0.0.0.0.0.0.0.0.0.0

**Comment by PikyCZ** [comment]
:/ rewrite this project

**Comment by lsw46** [comment]
How long does it take?
I need to use this plugin
:D
:+1:

**Comment by PikyCZ** [comment]
I'll fix it for 2-3 days .. :)

**Comment by Creeperface01** [comment]
use latest nukkit -,-

**Comment by Creeperface01** [comment]
close ;)

**Comment by lsw46** [comment]
sure？

**Comment by Creeperface01** [comment]
yes

**Comment by lsw46** [comment]
no no no   
crash the server 
use the least version

**Comment by lsw46** [comment]
0.0

**Comment by Creeperface01** [comment]
it works, use latest nukkit and plugin version

**Comment by NycuRO** [comment]
Confirmed.

**Comment by Creeperface01** [comment]
what is confirmed? crash? :D

**Comment by NycuRO** [comment]
Yes.

**Comment by Creeperface01** [comment]
but it works well for me :D

**Comment by NycuRO** [comment]
For you.

**Comment by Creeperface01** [comment]
he has old version of the plugin there is no longer package de.kniffo80 :D

**Comment by NycuRO** [comment]
Give me one link with .jar and nukkit version .

**Comment by Creeperface01** [comment]
https://www.dropbox.com/s/fk1gzx367ndq8je/MobPlugin.jar?dl=0

**Comment by Creeperface01** [comment]
with latest nukkit
