### ISSUE TITLE
Command Spawning Problem

### ISSUE THREAD

**Issue by ZephyR626** [PikyCZ/MobPlugin#30]
The mobs cant be spawned by the system automatically or through using the command on the server control panel. When I using the command(/mob spawn pig) in game, it shows "unable to spawn pig". When I using the command in server control panel, these appear...

> mob spawn pig
21:41:17 [INFO] An unknown error occurred while attempting to perform this command
21:41:17 [CRITICAL] Unhandled exception executing command 'mob spawn pig' in mob: java.lang.ClassCastException: cn.nukkit.command.ConsoleCommandSender cannot be cast to cn.nukkit.Player
at com.pikycz.mobplugin.MobPlugin.onCommand(MobPlugin.java:151)
at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
at cn.nukkit.Server.dispatchCommand(Server.java:652)
at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
at cn.nukkit.Server.tick(Server.java:1018)
at cn.nukkit.Server.tickProcessor(Server.java:808)
at cn.nukkit.Server.start(Server.java:787)
at cn.nukkit.Server.<init>(Server.java:472)
at cn.nukkit.Nukkit.main(Nukkit.java:68)

21:41:17 [ALERT] java.lang.ClassCastException: cn.nukkit.command.ConsoleCommandSender cannot be cast to cn.nukkit.Player
at com.pikycz.mobplugin.MobPlugin.onCommand(MobPlugin.java:151)
at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
at cn.nukkit.Server.dispatchCommand(Server.java:652)
at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
at cn.nukkit.Server.tick(Server.java:1018)
at cn.nukkit.Server.tickProcessor(Server.java:808)
at cn.nukkit.Server.start(Server.java:787)
at cn.nukkit.Server.<init>(Server.java:472)
at cn.nukkit.Nukkit.main(Nukkit.java:68)

I have checked that the difficulty of the world is 3(hard), the setting(auto-spawn) of the server in properties files, but there still a problem.

**Comment by PikyCZ** [comment]
use /mob spawn Pig and set difficulty to normal

**Comment by PikyCZ** [comment]
example /mob spawn Pig,Cow,Sheep .. 
this is not a bug .. 
you must send command from game not from console ..
here is code  -> playerThatSpawns = ( Player ) commandSender;
but yeah i can cancle command from console

**Comment by erickwoc** [comment]
I also have the same problem.
Logs are below:

-------------------------------
> 2017-6-21 17:33:57 [CRITICAL] 于 mob 执行指令 "mob spawn Pig" 时，出现了未被处理的错误： java.lang.ClassCastException: cn.nukkit.command.ConsoleCommandSender cannot be cast to cn.nukkit.Player
        at com.pikycz.mobplugin.MobPlugin.onCommand(MobPlugin.java:129)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:651)
        at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:1017)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
 2017-6-21 17:33:57 [ALERT]java.lang.ClassCastException: cn.nukkit.command.ConsoleCommandSender cannot be cast to cn.nukkit.Player
        at com.pikycz.mobplugin.MobPlugin.onCommand(MobPlugin.java:129)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:651)
        at cn.nukkit.command.CommandReader$1.run(CommandReader.java:78)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:282)
        at cn.nukkit.Server.tick(Server.java:1017)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

Difficulty: normal
Client version: 1.0.8 on Android
Plugin version: 1.0#307
Server version: 1.0dev
API version: 1.0.0
Supported MCPE version: 1.0.9

**Comment by matt404** [comment]
I'm experiencing this same issue when trying to upgrade NovaMobs to use the latest version of Nukkit.  `mob summon Pig` gives the same error.  Also tried `mob spawn Pig` which doen't work because 'spawn' is not mapped in the code.  Any guidance on how to get around this would be appreciated.

**Comment by Creeperface01** [comment]
Do not send commands from console

**Comment by matt404** [comment]
haha, just found that out right as you responded.  thanks for the quick response!
