### ISSUE TITLE
Instant crash as soon as a player spawns

### ISSUE THREAD

**Issue by Vinnpinn** [PikyCZ/MobPlugin#37]
Here is the Server output:

17:06:38 [EMERGENCY] Exception happened while ticking server
17:06:38 [ALERT] java.lang.NoSuchMethodError: cn.nukkit.block.Block.getSide(I)Lcn/nukkit/block/Block;
	at com.pikycz.mobplugin.entities.WalkingEntity.checkJump(WalkingEntity.java:105)
	at com.pikycz.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:172)
	at com.pikycz.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:229)
	at cn.nukkit.level.Level.doTick(Level.java:762)
	at cn.nukkit.Server.checkTickUpdates(Server.java:946)
	at cn.nukkit.Server.tick(Server.java:1021)
	at cn.nukkit.Server.tickProcessor(Server.java:808)
	at cn.nukkit.Server.start(Server.java:787)
	at cn.nukkit.Server.<init>(Server.java:472)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

17:06:38 [ALERT] 
"Thread-11" Id=24 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.Player$1.run(Player.java:503)

"threadDeathWatcher-3-1" Id=23 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

"nioEventLoopGroup-2-1" Id=22 RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@4c2bb6e0
	-  locked java.util.Collections$UnmodifiableSet@3e62d773
	-  locked sun.nio.ch.EPollSelectorImpl@4ef74c30
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	...

"Nukkit Asynchronous Task Handler #3" Id=21 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@7283d3eb
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@7283d3eb
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #2" Id=20 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@7283d3eb
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@7283d3eb
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #1" Id=19 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@7283d3eb
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@7283d3eb
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Nukkit Asynchronous Task Handler #0" Id=18 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@7283d3eb
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@7283d3eb
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"RakNet Thread #14" Id=14 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
	at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
	at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
	at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"Console" Id=9 RUNNABLE (in native)
	at java.io.FileInputStream.read0(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:207)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	-  locked jline.internal.NonBlockingInputStream@638ef7ed
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
	-  locked jline.internal.NonBlockingInputStream@638ef7ed
	at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
	-  locked jline.internal.NonBlockingInputStream@638ef7ed
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2143)
	...

"NonBlockingInputStreamThread" Id=13 WAITING on jline.internal.NonBlockingInputStream@638ef7ed owned by "Console" Id=9
	at java.lang.Object.wait(Native Method)
	-  waiting on jline.internal.NonBlockingInputStream@638ef7ed
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	at java.lang.Thread.run(Thread.java:748)

"process reaper" Id=11 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4bff7da0
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4bff7da0
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"process reaper" Id=10 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4bff7da0
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4bff7da0
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	...

"Thread-0" Id=8 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:224)
	at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@3f1d2e23
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@3f1d2e23
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@536dbea0
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@536dbea0
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" Id=1 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:111)
	at cn.nukkit.Server.tickProcessor(Server.java:823)
	at cn.nukkit.Server.start(Server.java:787)
	at cn.nukkit.Server.<init>(Server.java:472)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by PikyCZ** [comment]
[MobPlugin] registerEntites: done. 
[MobPlugin] Plugin loaded successfully.
[MobPlugin] Plugin enabling successful [aiEnabled:true] [autoSpawnTick:800]
PikyCZ logged in with entity id 2 at (Lobby, 137.0, 66.5, 106.0)
[INFO] [Welcome] Player PikyCZ logged-in!

**Comment by joffie87** [comment]
I'm having the same issue with a fresh server, no other plugins.
