### ISSUE TITLE
Instant crash as soon as a player spawns on new #1722 CI build 429 Caused by "World"

### ISSUE THREAD

**Issue by dcmwai** [PikyCZ/MobPlugin#39]
Dear PikyCZ, 

new CI build from 429
https://circleci.com/gh/Creeperface01/Nukkit/429#artifacts/containers/0
with the same plugin like my server do it is ok.

I check and found problem was caused by world (If I removed the whole world folder, it will be OK)
My question is what can I do?

I've tried removedmobs but didn't seem fix the crash.
any advise on what to do?

19:11:04 [EMERGENCY] Exception happened while ticking server
19:11:04 [ALERT] java.lang.NoSuchMethodError: com.pikycz.mobplugin.entities.WalkingEntity.getDirection()Ljava/lang/Integer;
        at com.pikycz.mobplugin.entities.WalkingEntity.checkJump(WalkingEntity.java:100)
        at com.pikycz.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:171)
        at com.pikycz.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:219)
        at cn.nukkit.level.Level.doTick(Level.java:811)
        at cn.nukkit.Server.checkTickUpdates(Server.java:945)
        at cn.nukkit.Server.tick(Server.java:1020)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

19:11:04 [ALERT]
"Thread-18" Id=33 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.Player$1.run(Player.java:503)

"threadDeathWatcher-3-1" Id=32 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Unknown Source)

"Nukkit Asynchronous Task Handler #11" Id=31 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #10" Id=30 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #9" Id=29 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #8" Id=28 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #6" Id=26 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #5" Id=25 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #4" Id=24 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #3" Id=23 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"Nukkit Asynchronous Task Handler #1" Id=21 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@440eaa07
        at java.util.concurrent.locks.LockSupport.park(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ...

"nioEventLoopGroup-2-1" Id=19 RUNNABLE (in native)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@7fc7c4a
        -  locked java.util.Collections$UnmodifiableSet@7aa9e414
        -  locked sun.nio.ch.WindowsSelectorImpl@53a5e217
        at sun.nio.ch.SelectorImpl.select(Unknown Source)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
        ...

"Abandoned connection cleanup thread" Id=18 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@624a24f6
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@624a24f6
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)

"RakNet Thread #15" Id=15 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
        at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
        at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
        at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"Console" Id=12 RUNNABLE (in native)
        at org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method)
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:811)
        at org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:842)
        at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97)
        at jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214)
        at jline.WindowsTerminal.access$000(WindowsTerminal.java:54)
        at jline.WindowsTerminal$1.read(WindowsTerminal.java:156)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
        -  locked jline.internal.NonBlockingInputStream@6b00ad9
        ...

"NonBlockingInputStreamThread" Id=14 WAITING on jline.internal.NonBlockingInputStream@6b00ad9 owned by "Console" Id=12
        at java.lang.Object.wait(Native Method)
        -  waiting on jline.internal.NonBlockingInputStream@6b00ad9
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
        at java.lang.Thread.run(Unknown Source)

"Thread-0" Id=11 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:224)
        at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)

"Attach Listener" Id=5 RUNNABLE

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@338cc75f
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@338cc75f
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@4f453e63
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@4f453e63
        at java.lang.Object.wait(Unknown Source)
        at java.lang.ref.Reference.tryHandlePending(Unknown Source)
        at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"main" Id=1 RUNNABLE
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
        at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:111)
        at cn.nukkit.Server.tickProcessor(Server.java:822)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by twixi** [comment]
i have this error too

**Comment by dcmwai** [comment]
I seem to find some mob is Stuck on the loop... Strange...

**Comment by dcmwai** [comment]
Using new version here seem to fixed the problem
https://circleci.com/gh/PikyCZ/MobPlugin/250#artifacts/containers/0

**Comment by PikyCZ** [comment]
..

**Comment by twixi** [comment]
`19:41:01 [INFO] Steve3[/192.168.0.200:19132] logged in with entity id 1 at (worl
d, 36.0506, 69.0, 84.1865)
19:41:02 [EMERGENCY] Exception happened while ticking server
19:41:02 [ALERT] java.lang.NoSuchMethodError: com.pikycz.mobplugin.entities.Walk
ingEntity.getDirection()Ljava/lang/Integer;
        at com.pikycz.mobplugin.entities.WalkingEntity.checkJump(WalkingEntity.j
ava:100)
        at com.pikycz.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.
java:171)
        at com.pikycz.mobplugin.entities.animal.WalkingAnimal.onUpdate(WalkingAn
imal.java:92)
        at cn.nukkit.level.Level.doTick(Level.java:811)
        at cn.nukkit.Server.checkTickUpdates(Server.java:945)
        at cn.nukkit.Server.tick(Server.java:1020)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

19:41:02 "Server stopped. It'll be restarted in 3 second(s). You can press Ctrl+
C to stop the restart process if you don't want to restart."`

**Comment by twixi** [comment]
`2017-5-16 19:48:46 [INFO] Steve3[/192.168.0.200:19132] logged in with entity id 1 at (world, 128.0, 68.0, 128.0732)
2017-5-16 19:48:57 [INFO] Steve3 joined the game
2017-5-16 19:50:19 [INFO] 2001 false
2017-5-16 19:50:20 [EMERGENCY] Exception happened while ticking server
2017-5-16 19:50:20 [ALERT] java.lang.NoSuchMethodError: com.pikycz.mobplugin.entities.WalkingEntity.getDirection()Ljava/lang/Integer;
	at com.pikycz.mobplugin.entities.WalkingEntity.checkJump(WalkingEntity.java:100)
	at com.pikycz.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:171)
	at com.pikycz.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:219)
	at cn.nukkit.level.Level.doTick(Level.java:811)
	at cn.nukkit.Server.checkTickUpdates(Server.java:945)
	at cn.nukkit.Server.tick(Server.java:1020)
	at cn.nukkit.Server.tickProcessor(Server.java:807)
	at cn.nukkit.Server.start(Server.java:786)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-5-16 19:50:20 [ALERT] 
"threadDeathWatcher-3-1" Id=27 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)


"Nukkit Asynchronous Task Handler #7" Id=26 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@87d9a01
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@87d9a01
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Nukkit Asynchronous Task Handler #6" Id=25 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@87d9a01
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@87d9a01
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Nukkit Asynchronous Task Handler #4" Id=23 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@87d9a01
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@87d9a01
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"Nukkit Asynchronous Task Handler #2" Id=21 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@87d9a01
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@87d9a01
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...


"nioEventLoopGroup-2-1" Id=19 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@7e5b621b
	-  locked java.util.Collections$UnmodifiableSet@10177794
	-  locked sun.nio.ch.WindowsSelectorImpl@e5c2463
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
	...


"Thread-7" Id=18 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at zingding.RealHunger$1.run(RealHunger.java:66)
	at java.lang.Thread.run(Unknown Source)


"Abandoned connection cleanup thread" Id=16 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@6a950a3b
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@6a950a3b
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)


"RakNet Thread #13" Id=13 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
	at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
	at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
	at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)


"Console" Id=10 RUNNABLE (in native)
	at org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method)
	at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:811)
	at org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:842)
	at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97)
	at jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214)
	at jline.WindowsTerminal.access$000(WindowsTerminal.java:54)
	at jline.WindowsTerminal$1.read(WindowsTerminal.java:156)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	-  locked jline.internal.NonBlockingInputStream@4f7be6c8
	...


"NonBlockingInputStreamThread" Id=12 WAITING on jline.internal.NonBlockingInputStream@4f7be6c8 owned by "Console" Id=10
	at java.lang.Object.wait(Native Method)
	-  waiting on jline.internal.NonBlockingInputStream@4f7be6c8
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	at java.lang.Thread.run(Unknown Source)


"Thread-0" Id=9 RUNNABLE
	at java.lang.Object.wait(Native Method)
	at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:222)
	at cn.nukkit.utils.MainLogger.run(MainLogger.java:213)


"Attach Listener" Id=5 RUNNABLE


"Signal Dispatcher" Id=4 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@647b9364
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@647b9364
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@b6bccb4
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@b6bccb4
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference.tryHandlePending(Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)


"main" Id=1 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:111)
	at cn.nukkit.Server.tickProcessor(Server.java:822)
	at cn.nukkit.Server.start(Server.java:786)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

`
