### ISSUE TITLE
Exception happened while ticking server

### ISSUE THREAD

**Issue by PetteriM1** [PikyCZ/MobPlugin#40]
I got this with latest Nukkit version:

2017-5-19 21:12:49 [EMERGENCY] Exception happened while ticking server
2017-5-19 21:12:49 [ALERT] java.lang.NoSuchMethodError: com.pikycz.mobplugin.entities.WalkingEntity.getDirection()Ljava/lang/Integer;
	at com.pikycz.mobplugin.entities.WalkingEntity.checkJump(WalkingEntity.java:100)
	at com.pikycz.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:171)
	at com.pikycz.mobplugin.entities.animal.WalkingAnimal.onUpdate(WalkingAnimal.java:92)
	at cn.nukkit.level.Level.doTick(Level.java:812)
	at cn.nukkit.Server.checkTickUpdates(Server.java:945)
	at cn.nukkit.Server.tick(Server.java:1020)
	at cn.nukkit.Server.tickProcessor(Server.java:807)
	at cn.nukkit.Server.start(Server.java:786)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-5-19 21:12:49 [ALERT] 
"threadDeathWatcher-3-1" Id=24 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)

"Nukkit Asynchronous Task Handler #6" Id=23 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@55746340
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@55746340
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"Nukkit Asynchronous Task Handler #5" Id=22 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@55746340
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@55746340
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"Nukkit Asynchronous Task Handler #4" Id=21 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@55746340
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@55746340
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"Nukkit Asynchronous Task Handler #3" Id=20 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@55746340
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@55746340
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
	at java.util.concurrent.SynchronousQueue.take(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	...

"nioEventLoopGroup-2-1" Id=16 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@6a0c7af6
	-  locked java.util.Collections$UnmodifiableSet@7f1ad846
	-  locked sun.nio.ch.WindowsSelectorImpl@5d5ae6aa
	at sun.nio.ch.SelectorImpl.select(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
	...

"RakNet Thread #13" Id=13 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
	at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
	at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
	at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"Console" Id=10 RUNNABLE (in native)
	at org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method)
	at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:811)
	at org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:842)
	at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97)
	at jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214)
	at jline.WindowsTerminal.access$000(WindowsTerminal.java:54)
	at jline.WindowsTerminal$1.read(WindowsTerminal.java:156)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	-  locked jline.internal.NonBlockingInputStream@2bc2e022
	...

"NonBlockingInputStreamThread" Id=12 WAITING on jline.internal.NonBlockingInputStream@2bc2e022 owned by "Console" Id=10
	at java.lang.Object.wait(Native Method)
	-  waiting on jline.internal.NonBlockingInputStream@2bc2e022
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	at java.lang.Thread.run(Unknown Source)

"Thread-0" Id=9 RUNNABLE (in native)
	at java.io.FileOutputStream.close0(Native Method)
	at java.io.FileOutputStream.access$000(Unknown Source)
	at java.io.FileOutputStream$1.close(Unknown Source)
	at java.io.FileDescriptor.closeAll(Unknown Source)
	-  locked java.io.FileDescriptor@2210e466
	at java.io.FileOutputStream.close(Unknown Source)
	at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at sun.nio.cs.StreamEncoder.close(Unknown Source)
	-  locked java.io.OutputStreamWriter@be1c08a
	at java.io.OutputStreamWriter.close(Unknown Source)
	...

"Attach Listener" Id=5 RUNNABLE

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@10408ea
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@10408ea
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.ReferenceQueue.remove(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@3d7b3b18
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@3d7b3b18
	at java.lang.Object.wait(Unknown Source)
	at java.lang.ref.Reference.tryHandlePending(Unknown Source)
	at java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"main" Id=1 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
	at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:111)
	at cn.nukkit.Server.tickProcessor(Server.java:822)
	at cn.nukkit.Server.start(Server.java:786)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by YaBoiBalAnce** [comment]
i can confirm this as well

**Comment by PikyCZ** [comment]
please use latest version mobplugin please.. :/

**Comment by Black-Bass** [comment]
I use latest version, and i still this problem

**Comment by Creeperface01** [comment]
Probably not.. Just downloaded latest nukkit and compiled latest mobplugin and works

**Comment by Black-Bass** [comment]
@Creeperface01 I'm not an idiot, ok man. Good luck!

**Comment by Creeperface01** [comment]
For me it does, and error you reported is fixed

**Comment by ivzakirov** [comment]
[MobPlugin-1.0.4.jar](https://github.com/PikyCZ/MobPlugin/releases/download/1.0/MobPlugin-1.0.4.jar) - is it latest version? I can't compile from source.

**Comment by PetteriM1** [comment]
I used 1.0.4 when I got this error.

**Comment by ivzakirov** [comment]
Finally I have compiled [current](https://github.com/PikyCZ/MobPlugin/commit/d0db8edc3a0fb0cd4c1223c4e9acc2abbccc0062) version from source. There is no error anymore. You need maven and jdk to compile it.
But I confirm that latest available binary [MobPlugin-1.0.4.jar](https://github.com/PikyCZ/MobPlugin/releases) **has** this error.

**Comment by PetteriM1** [comment]
Can someone send compiled jar because I don't know how and no time to do it?

**Comment by ivzakirov** [comment]
PetteriM1, go to [https://circleci.com/gh/PikyCZ/MobPlugin/tree/master/](https://circleci.com/gh/PikyCZ/MobPlugin/tree/master/), then choose latest successful build and go to "Artifacts" tab. There you can download jar file. A bit tricky, isn't it?

**Comment by Creeperface01** [comment]
Then its circle CI bug? Or idk

**Comment by ivzakirov** [comment]
Creeperface01, there is no bug now. AFAIK this bug solved but author did not add new [release](https://github.com/PikyCZ/MobPlugin/releases). So you should download automatically built jar from Circle CI. Is it clear?

**Comment by PetteriM1** [comment]
Ok

**Comment by Creeperface01** [comment]
Yes this is why I didnt understand whats wrong, of course you should download from circle CI
