### ISSUE TITLE
Issue with /mob spawn <mob>

### ISSUE THREAD

**Issue by DxDen1004** [PikyCZ/MobPlugin#42]
Hello,

I've been playing around with your nice plugin, but I'm unable to spawn mobs using the /mob spawn command. I receive the following error:

`5 [CRITICAL] Unhandled exception executing command 'mob spawn' in mob: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.pikycz.mobplugin.MobPlugin.onCommand(MobPlugin.java:123)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:651)
        at cn.nukkit.Player.handleDataPacket(Player.java:2997)
        at cn.nukkit.network.Network.processPackets(Network.java:185)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1896)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:64)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1009)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)`

Any idea about how to fix this?
Thankyou.

**Comment by PikyCZ** [comment]
commands fixed
