### ISSUE TITLE
[CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerInteractEvent'

### ISSUE THREAD

**Issue by PetteriM1** [PikyCZ/MobPlugin#50]
Server spam this when players online:

[CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerInteractEvent' to 'MobPlugin v1.0': null on com.pikycz.mobplugin.MobPlugin
2017-7-16 10:26:39 [ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.level.Level.useItemOn(Level.java:1989)
	at cn.nukkit.Player.handleDataPacket(Player.java:2231)
	at cn.nukkit.network.Network.processPackets(Network.java:175)
	at cn.nukkit.network.Network.processBatch(Network.java:151)
	at cn.nukkit.Player.handleDataPacket(Player.java:1932)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:75)
	at cn.nukkit.Server.tick(Server.java:996)
	at cn.nukkit.Server.tickProcessor(Server.java:794)
	at cn.nukkit.Server.start(Server.java:773)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NoSuchMethodError: cn.nukkit.event.player.PlayerInteractEvent.getAction()I
	at com.pikycz.mobplugin.MobPlugin.PlayerInteractEvent(MobPlugin.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 16 more

**Comment by PikyCZ** [comment]
Use latest build
