### ISSUE TITLE
I don't know what this problem is..

### ISSUE THREAD

**Issue by erickwoc** [PikyCZ/MobPlugin#53]
I tried to run `/mob spawn pig` in game and I get nothing but "cannont run this command"
And this occurs when I try to run `mob spawn pig` in the console

====================================

2017-7-24 23:34:16 [CRITICAL] 于 mob 执行指令 "mob spawn pig" 时，出现了未被处理的错误： java.lang.ClassCastException: cn.nukkit.command.ConsoleCommandSender cannot be cast to cn.nukkit.Player
        at com.pikycz.mobplugin.MobPlugin.onCommand(MobPlugin.java:130)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:638)
        at cn.nukkit.command.CommandReader.lambda$run$58(CommandReader.java:75)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
        at cn.nukkit.Server.tick(Server.java:1004)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-7-24 23:34:16 [ALERT] java.lang.ClassCastException: cn.nukkit.command.ConsoleCommandSender cannot be cast to cn.nukkit.Player
        at com.pikycz.mobplugin.MobPlugin.onCommand(MobPlugin.java:130)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:638)
        at cn.nukkit.command.CommandReader.lambda$run$58(CommandReader.java:75)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
        at cn.nukkit.Server.tick(Server.java:1004)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

========================================

nukkit version: Nukkit 1.0dev
API version:  1.0.0
support Minecraft: PE v1.1.3 (Protocol Version: 113)
MobPlugin version: 1.0#323

**Comment by PikyCZ** [comment]
i mean you not read Readme -_- 

/mob spawn <mob_name> | Spawn mob (mob_name write always with a capital letter.. For example: Pig,Zombie)
